force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Guide__c/Guide__c.object-meta.xml
<CustomObject>
    <description>Guides guide the trek.</description>
    <label>Guide</label>
    <nameField>
        <label>Guide Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trek__c/Trek__c.object-meta.xml
<CustomObject>
    <description>Trek Overview</description>
    <label>Trek</label>
    <nameField>
        <label>Trek Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Treks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trek_Booking__c/Trek_Booking__c.object-meta.xml
<CustomObject>
    <label>Trek Booking</label>
    <nameField>
        <label>Trek Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trek Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trek_Booking__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Trek Bookings</relationshipLabel>
    <relationshipName>Trek_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trek_Booking__c/fields/Guide__c.field-meta.xml
<CustomField>
    <fullName>Guide__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Guide</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Guide is Already Assigned Cannot Assign Again.</errorMessage>
        <filterItems>
            <field>Guide__c.isBooked__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <filterItems>
            <field>$Source.Booking_Status__c</field>
            <operation>notEqual</operation>
            <value>Confirmed</value>
        </filterItems>
        <infoMessage>Only available guides can be assigned.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Guide__c</referenceTo>
    <relationshipLabel>Trek Bookings</relationshipLabel>
    <relationshipName>Trek_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trek_Booking__c/fields/Trek__c.field-meta.xml
<CustomField>
    <fullName>Trek__c</fullName>
    <description>Hello</description>
    <label>Trek</label>
    <referenceTo>Trek__c</referenceTo>
    <relationshipLabel>Trek Bookings</relationshipLabel>
    <relationshipName>Trek_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ExpeditionDashboardController.cls
public with sharing class ExpeditionDashboardController {

    @AuraEnabled(cacheable=true)
    public static Map<String, Integer> getDashboardCounts() {
        Map<String, Integer> counts = new Map<String, Integer>();

        counts.put('clients', [SELECT COUNT() FROM Client__c]);
        counts.put('treks', [SELECT COUNT() FROM Trek__c]);
        counts.put('guides', [SELECT COUNT() FROM Guide__c]);
        counts.put('bookings', [SELECT COUNT() FROM Trek_Booking__c]);

        return counts;
    }
}